server:
  port: 8090

spring:
  boot:
    admin:
      monitor:
        default-timeout: 10000ms
  security:
    user:
      name: admin
      password: 1234
  cloud:
    loadbalancer:
      enabled: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka/}
#    disable-delta: true
#    registry-fetch-interval-seconds: 10

logging:
  level:
    com:
      netflix:
        discovery: ERROR